ARG VERSION
FROM --platform=amd64 ghcr.io/actions/actions-runner:${VERSION}

ENV HOMEBREW_NO_ANALYTICS=1 \
  HOMEBREW_NO_ENV_HINTS=1 \
  HOMEBREW_NO_INSTALL_CLEANUP=1 \
  DEBCONF_NONINTERACTIVE_SEEN=true \
  DEBIAN_FRONTEND="noninteractive" \
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

USER root

RUN \
  apt-get update && apt-get upgrade -y \
  && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  gcc \
  git \
  jo \
  jq \
  # libgmp \
  # libyaml-0 \
  moreutils \
  unrar \
  unzip \
  wget \
  zip \
  && rm -rf /var/lib/apt/lists/*

ENV RUNNER_TOOL_CACHE=/opt/hostedtoolcache
RUN mkdir ${RUNNER_TOOL_CACHE} \
  && chgrp docker ${RUNNER_TOOL_CACHE} \
  && chmod g+rwx ${RUNNER_TOOL_CACHE}

USER runner

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
